"""add iso models 2

Revision ID: f42722ced9a2
Revises: 
Create Date: 2025-08-26 20:39:23.240839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import os
SCHEMA = os.getenv("DB_SCHEMA", "iso")

# revision identifiers, used by Alembic.
revision: str = 'f42722ced9a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
print(SCHEMA)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog',
    sa.Column('catalog_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('catalog_key', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_hierarchical', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('catalog_id'),
    sa.UniqueConstraint('catalog_key'),
    schema=SCHEMA
    )
    op.create_table('empresa',
    sa.Column('empresa_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre_legal', sa.Text(), nullable=False),
    sa.Column('rfc', sa.Text(), nullable=True),
    sa.Column('estatus', sa.Text(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('empresa_id'),
    schema=SCHEMA
    )
    op.create_table('areas',
    sa.Column('area_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], [f'{SCHEMA}.empresa.empresa_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('area_id'),
    schema=SCHEMA
    )
    op.create_index('uq_areas_empresa_nombre', 'areas', ['empresa_id', sa.literal_column('lower(nombre)')], unique=True, schema=SCHEMA)
    op.create_table('catalog_item',
    sa.Column('item_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('catalog_id', sa.BigInteger(), nullable=False),
    sa.Column('empresa_id', sa.BigInteger(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('parent_item_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['catalog_id'], [f'{SCHEMA}.catalog.catalog_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['empresa_id'], [f'{SCHEMA}.empresa.empresa_id'], ),
    sa.ForeignKeyConstraint(['parent_item_id'], [f'{SCHEMA}.catalog_item.item_id'], ),
    sa.PrimaryKeyConstraint('item_id'),
    schema=SCHEMA
    )
    op.create_table('permiso',
    sa.Column('permiso_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.BigInteger(), nullable=True),
    sa.Column('codigo', sa.Text(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], [f'{SCHEMA}.empresa.empresa_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('permiso_id'),
    schema=SCHEMA
    )
    op.create_index('uq_permiso_scope', 'permiso', ['empresa_id', sa.literal_column('upper(codigo)')], unique=True, schema=SCHEMA)
    op.create_table('rol',
    sa.Column('rol_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], [f'{SCHEMA}.empresa.empresa_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rol_id'),
    schema=SCHEMA
    )
    op.create_index('uq_rol_empresa_nombre', 'rol', ['empresa_id', sa.literal_column('lower(nombre)')], unique=True, schema=SCHEMA)
    op.create_table('rol_permiso',
    sa.Column('rol_id', sa.BigInteger(), nullable=False),
    sa.Column('permiso_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], [f'{SCHEMA}.permiso.permiso_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_id'], [f'{SCHEMA}.rol.rol_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id'),
    schema=SCHEMA
    )
    op.create_table('usuario',
    sa.Column('usuario_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('area_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], [f'{SCHEMA}.areas.area_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['empresa_id'], [f'{SCHEMA}.empresa.empresa_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id'),
    schema=SCHEMA
    )
    op.create_index('uq_usuario_empresa_email', 'usuario', ['empresa_id', sa.literal_column('lower(email)')], unique=True, schema=SCHEMA)
    op.create_table('activo',
    sa.Column('activo_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('tipo_item_id', sa.BigInteger(), nullable=False),
    sa.Column('estado_item_id', sa.BigInteger(), nullable=False),
    sa.Column('clasificacion_item_id', sa.BigInteger(), nullable=False),
    sa.Column('propietario_id', sa.BigInteger(), nullable=True),
    sa.Column('custodio_id', sa.BigInteger(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ubicacion', sa.Text(), nullable=True),
    sa.Column('fecha_adquisicion', sa.Date(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('numero_serie', sa.Text(), nullable=True),
    sa.Column('marca', sa.Text(), nullable=True),
    sa.Column('modelo', sa.Text(), nullable=True),
    sa.Column('imagen_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('area_item_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['area_item_id'], [f'{SCHEMA}.catalog_item.item_id'], ),
    sa.ForeignKeyConstraint(['clasificacion_item_id'], [f'{SCHEMA}.catalog_item.item_id'], ),
    sa.ForeignKeyConstraint(['custodio_id'], [f'{SCHEMA}.usuario.usuario_id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], [f'{SCHEMA}.empresa.empresa_id'], ),
    sa.ForeignKeyConstraint(['estado_item_id'], [f'{SCHEMA}.catalog_item.item_id'], ),
    sa.ForeignKeyConstraint(['propietario_id'], [f'{SCHEMA}.usuario.usuario_id'], ),
    sa.ForeignKeyConstraint(['tipo_item_id'], [f'{SCHEMA}.catalog_item.item_id'], ),
    sa.PrimaryKeyConstraint('activo_id'),
    schema=SCHEMA
    )
    op.create_table('documento',
    sa.Column('documento_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('codigo', sa.Text(), nullable=True),
    sa.Column('tipo_item_id', sa.BigInteger(), nullable=False),
    sa.Column('area_responsable_item_id', sa.BigInteger(), nullable=True),
    sa.Column('clasificacion_item_id', sa.BigInteger(), nullable=True),
    sa.Column('visible_empresa', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('creador_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['area_responsable_item_id'], [f'{SCHEMA}.catalog_item.item_id'], ),
    sa.ForeignKeyConstraint(['clasificacion_item_id'], [f'{SCHEMA}.catalog_item.item_id'], ),
    sa.ForeignKeyConstraint(['creador_id'], [f'{SCHEMA}.usuario.usuario_id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], [f'{SCHEMA}.empresa.empresa_id'], ),
    sa.ForeignKeyConstraint(['tipo_item_id'], [f'{SCHEMA}.catalog_item.item_id'], ),
    sa.PrimaryKeyConstraint('documento_id'),
    schema=SCHEMA
    )
    op.create_table('usuario_permiso',
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('permiso_id', sa.BigInteger(), nullable=False),
    sa.Column('concedido', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], [f'{SCHEMA}.permiso.permiso_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], [f'{SCHEMA}.usuario.usuario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'permiso_id'),
    schema=SCHEMA
    )
    op.create_table('usuario_rol',
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('rol_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], [f'{SCHEMA}.rol.rol_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], [f'{SCHEMA}.usuario.usuario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'rol_id'),
    schema=SCHEMA
    )
    op.create_table('documento_acl',
    sa.Column('acl_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('documento_id', sa.BigInteger(), nullable=False),
    sa.Column('empresa_id', sa.BigInteger(), nullable=True),
    sa.Column('rol_item_id', sa.BigInteger(), nullable=True),
    sa.Column('area_item_id', sa.BigInteger(), nullable=True),
    sa.Column('permiso_item_id', sa.BigInteger(), nullable=False),
    sa.Column('nivel', sa.Integer(), server_default='0', nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['area_item_id'], [f'{SCHEMA}.catalog_item.item_id'], ),
    sa.ForeignKeyConstraint(['documento_id'], [f'{SCHEMA}.documento.documento_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['empresa_id'], [f'{SCHEMA}.empresa.empresa_id'], ),
    sa.ForeignKeyConstraint(['permiso_item_id'], [f'{SCHEMA}.catalog_item.item_id'], ),
    sa.ForeignKeyConstraint(['rol_item_id'], [f'{SCHEMA}.catalog_item.item_id'], ),
    sa.PrimaryKeyConstraint('acl_id'),
    schema=SCHEMA
    )
    op.create_table('documento_version',
    sa.Column('version_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('documento_id', sa.BigInteger(), nullable=False),
    sa.Column('numero_version', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('justificacion', sa.Text(), nullable=True),
    sa.Column('estado_item_id', sa.BigInteger(), nullable=False),
    sa.Column('archivo_url', sa.Text(), nullable=True),
    sa.Column('creado_por_id', sa.BigInteger(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('aprobado_por_id', sa.BigInteger(), nullable=True),
    sa.Column('fecha_autorizacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['aprobado_por_id'], [f'{SCHEMA}.usuario.usuario_id'], ),
    sa.ForeignKeyConstraint(['creado_por_id'], [f'{SCHEMA}.usuario.usuario_id'], ),
    sa.ForeignKeyConstraint(['documento_id'], [f'{SCHEMA}.documento.documento_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['estado_item_id'], [f'{SCHEMA}.catalog_item.item_id'], ),
    sa.PrimaryKeyConstraint('version_id'),
    schema=SCHEMA
    )
    op.create_table('comentario_revision',
    sa.Column('comentario_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('version_id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=False),
    sa.Column('archivo_url', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('estatus_item_id', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['estatus_item_id'], [f'{SCHEMA}.catalog_item.item_id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], [f'{SCHEMA}.usuario.usuario_id'], ),
    sa.ForeignKeyConstraint(['version_id'], [f'{SCHEMA}.documento_version.version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comentario_id'),
    schema=SCHEMA
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentario_revision', schema=SCHEMA)
    op.drop_table('documento_version', schema=SCHEMA)
    op.drop_table('documento_acl', schema=SCHEMA)
    op.drop_table('usuario_rol', schema=SCHEMA)
    op.drop_table('usuario_permiso', schema=SCHEMA)
    op.drop_table('documento', schema=SCHEMA)
    op.drop_table('activo', schema=SCHEMA)
    op.drop_index('uq_usuario_empresa_email', table_name='usuario', schema=SCHEMA)
    op.drop_table('usuario', schema=SCHEMA)
    op.drop_table('rol_permiso', schema=SCHEMA)
    op.drop_index('uq_rol_empresa_nombre', table_name='rol', schema=SCHEMA)
    op.drop_table('rol', schema=SCHEMA)
    op.drop_index('uq_permiso_scope', table_name='permiso', schema=SCHEMA)
    op.drop_table('permiso', schema=SCHEMA)
    op.drop_table('catalog_item', schema=SCHEMA)
    op.drop_index('uq_areas_empresa_nombre', table_name='areas', schema=SCHEMA)
    op.drop_table('areas', schema=SCHEMA)
    op.drop_table('empresa', schema=SCHEMA)
    op.drop_table('catalog', schema=SCHEMA)
    # ### end Alembic commands ###
